# Generated by Django 4.2.30 on 2026-09-27 23:19

import complaints.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=24, unique=True)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='complaints/%Y/%m/', validators=[complaints.validators.validate_attachment])),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], default='submitted', max_length=16)),
                ('resolution_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'complaint categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', 'Submitted'), ('categorised', 'Re-categorised'), ('reviewed', 'Moved to review'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=16)),
                ('from_status', models.CharField(blank=True, choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=16)),
                ('to_status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under review'), ('escalated', 'Escalated'), ('resolved', 'Resolved')], max_length=16)),
                ('actor_label', models.CharField(help_text='Frozen display name, so the trail survives a user rename.', max_length=80)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='NULL when the action had no identifiable actor to record.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='complaint_actions', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='complaints.complaint')),
            ],
            options={
                'verbose_name': 'complaint status log entry',
                'verbose_name_plural': 'complaint status log',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to='complaints.complaintcategory'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Always NULL for an anonymous complaint.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='accounts.student'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(check=models.Q(('is_anonymous', False), ('student__isnull', True), _connector='OR'), name='anonymous_has_no_student'),
        ),
        migrations.AddConstraint(
            model_name='complaint',
            constraint=models.CheckConstraint(check=models.Q(('is_anonymous', True), ('student__isnull', False), _connector='OR'), name='named_complaint_has_a_student'),
        ),
    ]
