# Generated by Django 4.2.30 on 2026-09-27 23:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.CharField(help_text='e.g. 2025/2026', max_length=16)),
                ('semester', models.PositiveSmallIntegerField(choices=[(1, 'First semester'), (2, 'Second semester')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_records', to='accounts.student')),
            ],
            options={
                'ordering': ['session', 'semester'],
            },
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('course_advice', 'Course advice'), ('warning', 'Warning'), ('probation_alert', 'Probation alert')], max_length=32)),
                ('message', models.TextField()),
                ('gpa_at_generation', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='academics.academicrecord')),
            ],
            options={
                'ordering': ['kind'],
            },
        ),
        migrations.CreateModel(
            name='CourseResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_code', models.CharField(max_length=16)),
                ('course_title', models.CharField(blank=True, max_length=160)),
                ('credit_units', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('grade', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F')], max_length=1)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_results', to='academics.academicrecord')),
            ],
            options={
                'ordering': ['course_code'],
            },
        ),
        migrations.CreateModel(
            name='AdvisoryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('response', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('adviser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='advisory_requests', to='accounts.adviser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisory_requests', to='accounts.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='recommendation',
            constraint=models.UniqueConstraint(fields=('record', 'kind'), name='one_recommendation_per_kind_per_record'),
        ),
        migrations.AddConstraint(
            model_name='courseresult',
            constraint=models.UniqueConstraint(fields=('record', 'course_code'), name='one_result_per_course_per_record'),
        ),
        migrations.AddConstraint(
            model_name='academicrecord',
            constraint=models.UniqueConstraint(fields=('student', 'session', 'semester'), name='one_record_per_student_session_semester'),
        ),
    ]
